### ISSUE TITLE
The output directory as **absolute path** 

### ISSUE THREAD

**Issue by bluetomlee** [chenchunyong/webpack-dllPlugin#1]
/node_modules/_webpack@1.12.15@webpack/lib/DllModuleFactory.js:17
	callback(null, new DllModule(context, dependency.dependencies, dependency.name, dependency.type));
	^

TypeError: callback is not a function

**Comment by chenchunyong** [comment]
是由于全局性webpack版本过高导致的问题，请pull最新代码，运行npm run webpack-dll命令，
